class Erp {
  constructor () {
    this.id = null
    this.tipo_tamizaje = null
    this.llamada_entrante = null
    this.reporte_id = null
    this.tamizador_id = null
    this.afiliado_id = null
    this.tipo_identificacion = null
    this.identificacion = null
    this.nombre = null
    this.nombre1 = null
    this.nombre2 = null
    this.apellido1 = null
    this.apellido2 = null
    this.fecha_nacimiento = null
    this.acudiente = null
    this.sexo = null
    this.celular = null
    this.celular2 = null
    this.email = null
    this.si_eps = 1
    this.eps_id = null
    this.tipo_afiliacion = null
    this.direccion = null
    this.departamento_id = null
    this.municipio_id = null
    this.barrio_id = null
    this.persona_id = null
    this.regimen_especial = null
    this.observaciones = null
    this.localiza_persona = null
    this.contesta_encuesta = null
    this.duracion = 0
    this.infoviajero = null
    // x
    this.riesgo_procedencia = null
    this.riesgo_ocupacional = null
    this.riesgo_contacto = null
    this.diagnosticado_covid = null
    this.positivo_covid = null
    this.fecha_diagnostico = null
    this.coordenadas = null
    this.fecha_ultima_evolucion = null
    this.orden_medica_id = null
    this.reasignar = null
    this.evoluciones = []
    this.sintomas = []
    this.fecha_sintomas = null
    this.nexos = []
    this.muestras = []
    this.tamizador = null
    this.evolucion = null
    this.prueba_rapida = null
    this.resultado_prueba_rapida = null
    this.estado_prueba = null
    this.entidad_reporta_sivigila = null
    this.hospitalizado = null
    this.grupo_atencion_especial_id = null
    this.grupo_atencion_especial = null
    this.solicitud_prueba = 0
    this.clasificacion = null
    this.frecuencia_pulso = null
    this.saturacion_oxigeno = null
    this.temperatura = null
    this.no_efectividad = null
    this.codIpsBai = null
    //
    this.ips_bai = null
    this.signos_alarma = []
    this.created_at = null
    this.updated_at = null
    this.comorbilidades = []
  }
}

export default Erp
